# Generated by Django 5.1 on 2024-09-11 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("nodes", "0001_initial"),
        ("nodes", "0002_alter_chunk_unique_together_chunk_unique_node_chunk"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("size", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="nodes.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("index", models.IntegerField()),
                ("data", models.TextField(blank=True, null=True)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "unique_together": set(),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "index"), name="unique_node_chunk"
                    )
                ],
            },
        ),
    ]
