# Generated by Django 5.1 on 2024-09-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("node", "index"), name="unique_node_chunk"
            ),
        ),
    ]
