# Generated by Django 5.1.4 on 2024-12-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["parent"], name="nodes_node_parent__88b967_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["bucket_key"], name="nodes_node_bucket__474cb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["name"], name="nodes_node_name_cc1254_idx"),
        ),
    ]
